### ISSUE TITLE
Make cookie domain configurable

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/ala-cas-2.0#3]
Make cookie domain configurable to allow reuse in other countries/domains.

This is currently hardcoded to ala.org.au

https://github.com/AtlasOfLivingAustralia/ala-cas-2.0/blob/master/src/main/webapp/WEB-INF/spring-configuration/alaProxyAuthenticationCookieGenerator.xml

A workaround for this is to edit the XML file in the expanded war, but this isnt a good solution.
Needs to be read from external config.

**Comment by mbohun** [comment]
Preliminary ("runtime"/"live") test success on https://nci-cas4.ala.org.au (ala-cas test vm):
1. added `cas.testCookie="ABC-DEF"` into `cas.properties`
2. put `${cas.testCookie}` to
   `/var/lib/tomcat7/webapps/cas/WEB-INF/spring-configuration/alaProxyAuthenticationCookieGenerator.xml`
3. restarted tomcat
4. went to https://nci-cas4.ala.org.au/userdetails and logged in

the cookie is now set to: ABC-DEF

We can use our current approach and use ansible to set the cookie value in `cas.properties` file, like we already do for all the other `cas.properties` vars.
