### ISSUE TITLE
Remember me option not working

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/ala-cas-2.0#4]
When a user logs in and clicks the "remember me" tick-box, the user should not be asked to login in again for 4 weeks (from memory - maybe its 2 weeks?).

This is no longer working as, I am asked to login again after only 24 hours (the default session timeout if you don't click "remember me".

**Comment by ansell** [comment]
I can't see any references that map to 4 weeks, but there is a reference in the ansible configuration to rememberMe=1209600 which corresponds to 14 days if that time is in seconds:

https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/roles/cas2/templates/config/cas.properties

However, if that number is actually in milliseconds as usual for Java time variables, it only corresponds to 20 minutes. I will look further into how the CAS settings are propagated and interpreted to see if I can resolve that ambiguity.

**Comment by nickdos** [comment]
I had a look at my cookies and the cookie that was created when I logged in was called `ALA-Auth` and if I don't click "remember me" it has an expiry of "Expires: when the browser session ends" and if I do click the remember me option, then it expires in 3 months time (Jan 12):

![image](https://cloud.githubusercontent.com/assets/532845/19332111/d2a1f72c-9134-11e6-930f-e62a260baa1e.png)

So the cookie looks OK - maybe another ALA app is removing this cookie? Because when I go to a page and it asks me to login yet again, that cookie is no longer present.

**Comment by nickdos** [comment]
Looking at "edit this cookie" chrome ext, I see it has a tick next to "session". So I'm wondering if this is causing the issue?

![image](https://cloud.githubusercontent.com/assets/532845/19332535/a9a636fe-9138-11e6-9866-910f13a5ec06.png)

and the expiry is different now... something is modifying the cookie...

![image](https://cloud.githubusercontent.com/assets/532845/19332551/de5dc768-9138-11e6-9a66-344d4b602c4b.png)

**Comment by mbohun** [comment]
@nickdos the official CAS "rememberMe" feature documentation is at: https://apereo.github.io/cas/4.2.x/installation/Configuring-Authentication-Components.html#long-term-authentication (in fact i put the link to the doco into my ala-cas-2.0 [git commit comment](https://github.com/AtlasOfLivingAustralia/ala-cas-2.0/commit/29ca174d5161fa213463bb25c967db57b33faf56), although CAS people keep changing the domains, etc.); the "units" are described at: https://apereo.github.io/cas/4.2.x/installation/Configuring-LongTerm-Authentication.html#configuration

**Comment by ansell** [comment]
The Session attribute doesn't look like it is enabled for me when I click Remember Me.

Testing using Chrome, using the Cookies Chrome Extension (as my Firefox profile is permanently in session-only mode so won't help debug this):

![screen shot 2016-10-13 at 11 39 04 am](https://cloud.githubusercontent.com/assets/82365/19332625/c74032fe-9139-11e6-9909-2d3f0c57f2a8.png)

However Session is enabled, with no set Expiration date, if I don't check Remember Me:

![screen shot 2016-10-13 at 11 42 48 am](https://cloud.githubusercontent.com/assets/82365/19332699/35426b96-913a-11e6-9a6f-5b582c937466.png)

**Comment by ansell** [comment]
There is a sliding inactivity window documented in the link that @mbohun just posted. Those settings seem to be commented (ie, using the defaults) in our configuration, which may be part or the whole of the issue. Do we want the inactivity window to be the same as the maximum time?

**Comment by nickdos** [comment]
if I log in & check cookie, it says expires `Jan 12`. If I visit a page with `authenticateOnlyIfLoggedInFilterPattern` on biocache, like http://biocache.ala.org.au/occurrences/search?q=species_group%3ABirds+basis_of_record%3APreservedSpecimen#tab_mapView, then it still says `Jan 12`. 

But if visit different page with `authenticateOnlyIfLoggedInFilterPattern`, e.g. http://base.ala.org.au/datacheck, then the cookie then reports it expires with the session. Something about the base.ala.org.au is modifying the cookie to become session expiring...

**Comment by ansell** [comment]
I don't understand what is happening, but I can get Chrome extensions to say the cookie is "Session" based, but not expire it by logging into ala.org.au (not Session flagged), closing the browser and coming back to www.ala.org.au (ie, not using base.ala.org.au). I can then close the browser and come back in, and the cookie is still present with the Session attribute. 

The use of wordpress as the host for "www.ala.org.au" with its variety of cookies, some of which are Session based, may be confusing the issue as I still need to click on "Log in" after I open Chrome up each time.

Testing for just logging into collections.ala.org.au, I can come back in and the Session attribute is not checked. I close the browser and come back to collections.ala.org.au as many times as necessary without Session getting checked or the authentication changing and I am immediately logged in.

Testing for just logging into base.ala.org.au, the Session attribute is not checked initially if that was the first site I browsed to and then logged in, but it is checked after coming back in, and I am logged in after that restart. However, closing Chrome again and coming back in makes it look like I am not logged in. However, the "_ga" and "_gac" cookies for ala.org.au, and the "CASTGC" cookie for auth.ala.org.au are kept even though the "ALA-Auth" cookie is invalidated on the second restart, so clicking Log In after coming back in the second time doesn't require me to put any password in. After the passwordless login, the "ALA-Auth" cookie has Session enabled.

I will look into a testing regime to construct a matrix describing what is happening as it is confusing so far and there are different behaviours for all three of the hosts above, with collections.ala.org.au being the only one that behaves as expected, and even then, it only seems to behave as expected if you never visit either of the other two sites.

**Comment by ansell** [comment]
@nickdos Could you get me some version details about base.ala.org.au, specifically the ala-auth/cas-client versions and an ansible file to deploy and test it locally if possible, as I can't find its /buildInfo like I can for collections.ala.org.au/buildInfo

**Comment by mbohun** [comment]
Given that we have some samples of ALA apps that work and some samples of ALA apps that do have this problem would it be possible to compare the CAS configuration of these apps (usually stored in `/data/config/${app_name}.properties`)?
Mainly the content of these config files:
https://github.com/AtlasOfLivingAustralia/ala-cas/wiki/CAS-external-configuration

**Comment by nickdos** [comment]
sandbox (1.2-SNAPSHOT) config:

``` properties
# CAS Config
casProperties=casServerLoginUrl,serverName,centralServer,casServerName,uriFilterPattern,uriExclusionFilterPattern,authenticateOnlyIfLoggedInFilterPattern,casServerLoginUrlPrefix,gateway,casServerUrlPrefix,contextPath
serverName=http://base.ala.org.au
contextPath=/datacheck
grails.serverURL=http://base.ala.org.au/datacheck
casServerName=https://auth.ala.org.au
uriFilterPattern=/my-data
authenticateOnlyIfLoggedInFilterPattern=/,/.*
uriExclusionFilterPattern=/images.*,/css.*,/js.*,/less.*
casServerLoginUrl=https://auth.ala.org.au/cas/login
gateway=false
casServerUrlPrefix=https://auth.ala.org.au/cas
security.cas.logoutUrl=https://auth.ala.org.au/cas/logout
grails.serverURL=http://base.ala.org.au/datacheck
```

biocache (2.0.2) config:

``` properties
# Grails settings
grails.serverURL=http://biocache.ala.org.au
grails.resources.work.dir=/data/ala-hub/cache

# CAS Config
casProperties=casServerLoginUrl,serverName,centralServer,casServerName,uriFilterPattern,uriExclusionFilterPattern,authenticateOnlyIfLoggedInFilterPattern,casServerLoginUrlPrefix,gateway,casServerUrlPrefix,contextPath
serverName=http://biocache.ala.org.au
casServerName=https://auth.ala.org.au
uriFilterPattern=/admin,/admin/.*,/download,/download/.*
uriExclusionFilterPattern=/occurrences/shapeUpload,/images.*,/css.*,/js.*,.*json,/help/.*
authenticateOnlyIfLoggedInFilterPattern=/occurrences/(?!.+userAssertions|facet.+).+,/explore/your-area,/query,/proxy/download/.*,/
security.cas.appServerName=http://biocache.ala.org.au
security.cas.casServerUrlPrefix=https://auth.ala.org.au/cas
casServerUrlPrefix=https://auth.ala.org.au/cas
casServerLoginUrl=https://auth.ala.org.au/cas/login
gateway=false
contextPath=
disableCAS=false
security.cas.bypass=false
```

**Comment by mbohun** [comment]
``` diff
mbohun@linux-9gpe:/tmp> cat sandbox.properties.orig |sort > sandbox.properties
mbohun@linux-9gpe:/tmp> cat biocache.properties.orig | sort > biocache.properties

mbohun@linux-9gpe:/tmp> diff -y sandbox.properties biocache.properties
authenticateOnlyIfLoggedInFilterPattern=/,/.*                 | authenticateOnlyIfLoggedInFilterPattern=/occurrences/(?!.+use
casProperties=casServerLoginUrl,serverName,centralServer,casS   casProperties=casServerLoginUrl,serverName,centralServer,casS
casServerLoginUrl=https://auth.ala.org.au/cas/login             casServerLoginUrl=https://auth.ala.org.au/cas/login
casServerName=https://auth.ala.org.au                           casServerName=https://auth.ala.org.au
casServerUrlPrefix=https://auth.ala.org.au/cas                  casServerUrlPrefix=https://auth.ala.org.au/cas
contextPath=/datacheck                                        | contextPath=
                                                              > disableCAS=false
gateway=false                                                   gateway=false
grails.serverURL=http://base.ala.org.au/datacheck             | grails.resources.work.dir=/data/ala-hub/cache
grails.serverURL=http://base.ala.org.au/datacheck             | grails.serverURL=http://biocache.ala.org.au
security.cas.logoutUrl=https://auth.ala.org.au/cas/logout     | security.cas.appServerName=http://biocache.ala.org.au
serverName=http://base.ala.org.au                             | security.cas.bypass=false
uriExclusionFilterPattern=/images.*,/css.*,/js.*,/less.*      | security.cas.casServerUrlPrefix=https://auth.ala.org.au/cas
uriFilterPattern=/my-data                                     | serverName=http://biocache.ala.org.au
                                                              > uriExclusionFilterPattern=/occurrences/shapeUpload,/images.*,
                                                              > uriFilterPattern=/admin,/admin/.*,/download,/download/.*
```

**Comment by nickdos** [comment]
Chris just came in to my office and provided his theory of why this is happening and he was right... the cookies were a red herring... it turns out that CAS/AUTH is being restarted every night at 4am and as CAS is configured to store session data in memory, it is forgetting about any logged in users after the restart. The login term fix is to configure CAS to store session data in the userdetails database and a short term fix is to stop the cron job that is restarting tomcat every night.

**Comment by ansell** [comment]
The anomalies with the Session label did not look critical, as they did not require passwords to login again after browser restarts.

**Comment by matthewandrews** [comment]
Yep, this was due to the backup system I added to our AWS instances recently - each night services like apache/tomcat/mysql are stopped, a snapshot is taken, and services are restarted.  I've turned that off on auth for now.
