### ISSUE TITLE
Login page to use new skin

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/ala-cas-2.0#8]
https://auth.ala.org.au/cas/login

Would be good if it could use commonui css and HTML tempates from https://github.com/AtlasOfLivingAustralia/ala-bootstrap3

**Comment by sbearcsiro** [comment]
Completed in:
 - 93f72af
 - 7682021
 - 96112e7
 - 1e539d1
 - 6df05e4
 - 4adcf4b
 - 5219e27
 - b34e835
